Eshop_AspCore/Controllers/PayController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Eshop_AspCore.Data;
using Eshop_AspCore.Data.Models;
using Eshop_AspCore.Services;
using Eshop_AspCore.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Eshop_AspCore.Controllers
{
    public class PayController : Controller
    {
        [HttpPost]
        public IActionResult AddToCart(string userId, int CountProduct, int productId = 0)
        {
            ApplicationDbContext database = new ApplicationDbContext();

            try
            {
                if (User.Identity.IsAuthenticated)
                {
                    var qUser = database.Users.Where(c => c.Id == userId).FirstOrDefault();

                    var qProduct = database.Tbl_Products.Where(c => c.ProductId == productId).SingleOrDefault();

                    if (qUser == null && qProduct == null)
                        return RedirectToAction("Error", "Home");

                    var qShoppingCart = database.Tbl_ShoppingCart.Where(c => c.ProductId_FK == productId && c.UserId_FK == qUser.Id && c.Status == false).FirstOrDefault();

                    if (qShoppingCart != null)
                    {
                        qShoppingCart.ProductCount += CountProduct;
                        qShoppingCart.DateShop = DateTime.Now;

                        database.Tbl_ShoppingCart.Attach(qShoppingCart);
                        database.Entry(qShoppingCart).State = EntityState.Modified;
                        database.SaveChanges();

                    }
                    else
                    {
                        database.Tbl_ShoppingCart.Add(new ShoppingCart()
                        {
                            DateShop = DateTime.Now,
                            ProductCount = CountProduct,
                            ProductId_FK = qProduct.ProductId,
                            Status = false,
                            UserId_FK = qUser.Id,

                        });
                        database.SaveChanges();
                    }

                }
                else
                {
                    return RedirectToAction(nameof(AccountController.Login), "Account");
                }
            }
            catch
            {
                return RedirectToAction(nameof(HomeController.Error), "Home");
            }
            return Redirect(nameof(ShoppingCart));
        }

        public IActionResult ShoppingCart()
        {
            try
            {
                ApplicationDbContext database = new ApplicationDbContext();
                if (User.Identity.IsAuthenticated)
                {
                    string currentUser = User.Identity.Name;//get Username

                    var qUser = database.Users.Where(c => c.UserName == currentUser).FirstOrDefault();
                    if (qUser == null)
                        return null;

                    var qShoppingCart = database.Tbl_ShoppingCart.Where(c => c.UserId_FK == qUser.Id && c.Status == false && c.InvoiceId == null)
                                                                  .Include(c => c.Tbl_Products)
                                                                  .ThenInclude(c => c.Tbl_Gallery)
                                                                  .ToList();

                    List<VmShoppingCart> lstShopping = new List<VmShoppingCart>();

                    if (qShoppingCart.Count > 0)
                    {
                        foreach (var item in qShoppingCart)
                        {
                            VmShoppingCart vm = new VmShoppingCart();
                            vm.DateShop = item.DateShop;
                            vm.ID = item.ID;
                            vm.OffProduct = item.Tbl_Products.OffProduct;
                            vm.Price = item.Tbl_Products.Price;
                            vm.ProductCount = item.ProductCount;
                            vm.ProductId_FK = item.ProductId_FK;
                            vm.Status = false;
                            vm.ProductName = item.Tbl_Products.ProductNameFA;
                            vm.UserId_FK = item.UserId_FK;
                            vm.WeightPro = item.Tbl_Products.Weight;

                            string productImageName = database.Tbl_Gallery.Where(c => c.ProductId_FK == item.ProductId_FK && c.DefaultPicProduct == true).FirstOrDefault().PictureName;
                            vm.ProductImage = "/Files/Images/Products/" + productImageName;
                            if (item.Tbl_Products.OffProduct > 0 && item.Tbl_Products.OffProduct <= 100)
                            {
                                decimal p1 = Math.Ceiling(item.Tbl_Products.Price * item.Tbl_Products.OffProduct / 100);
                                decimal p2 = item.Tbl_Products.Price - p1;
                                decimal FinalPrice = (Math.Ceiling(p2 / 100) * 100);
                                vm.PriceWithOff = FinalPrice;
                            }
                            else
                            {
                                vm.PriceWithOff = item.Tbl_Products.Price;
                            }
                            lstShopping.Add(vm);
                        }
                        double Tax = database.Tbl_SettingSite.FirstOrDefault().Tax;
                        var sumPrice = lstShopping.Sum(c => c.PriceWithOff * c.ProductCount);
                        var sumWeight = lstShopping.Sum(c => c.WeightPro);
                        var qGetPriceByWeight = database.Tbl_Weight.Where(c => c.Weight_Min <= sumWeight && c.Weight_Max >= sumWeight).SingleOrDefault().Weight_Price;

                        ViewBag.Maliat = Tax;
                        ViewBag.PostagePrice = qGetPriceByWeight;

                        ViewBag.SumPrice = sumPrice;
                        ViewBag.SumWeight = sumWeight;


                    }
                    return View(lstShopping ?? null);

                }
                else
                {
                    return RedirectToAction(nameof(AccountController.Login), "Account");
                }
            }
            catch
            {
                return RedirectToAction(nameof(HomeController.Error), "Error");
            }


        }
        [HttpPost]
        public IActionResult RemoveProductOfShoppingCart(int shoppingId)
        {
            ApplicationDbContext database = new ApplicationDbContext();
            if (User.Identity.IsAuthenticated)
            {
                string currentUser = User.Identity.Name;//get Username

                var qUser = database.Users.Where(c => c.UserName == currentUser).FirstOrDefault();
                if (qUser == null)
                    return null;

                var qShoppingCart = database.Tbl_ShoppingCart.Where(c => c.UserId_FK == qUser.Id && c.Status == false && c.ID == shoppingId).SingleOrDefault();

                if (qShoppingCart == null)
                    return Redirect(nameof(ShoppingCart));

                database.Tbl_ShoppingCart.Remove(qShoppingCart);
                database.SaveChanges();
                return Redirect(nameof(ShoppingCart));
            }
            else
            {
                return RedirectToAction(nameof(AccountController.Login), "Account");
            }
        }
        public IActionResult RemoveAllProductOfShoppingCart()
        {
            ApplicationDbContext database = new ApplicationDbContext();
            if (User.Identity.IsAuthenticated)
            {
                string currentUser = User.Identity.Name;//get Username

                var qUser = database.Users.Where(c => c.UserName == currentUser).FirstOrDefault();
                if (qUser == null)
                    return null;

                var qShoppingCart = database.Tbl_ShoppingCart.Where(c => c.UserId_FK == qUser.Id && c.Status == false).ToList();

                if (qShoppingCart == null)
                    return Redirect(nameof(ShoppingCart));

                foreach (var item in qShoppingCart)
                {
                    database.Tbl_ShoppingCart.Remove(item);
                    database.SaveChanges();
                }
                return Redirect(nameof(ShoppingCart));
            }
            else
            {
                return RedirectToAction(nameof(AccountController.Login), "Account");
            }
        }
        public IActionResult CheckoutSendType(decimal FinalPrice)
        {
            ApplicationDbContext database = new ApplicationDbContext();
            if (User.Identity.IsAuthenticated)
            {
                string currentUser = User.Identity.Name;//get Username

                var qUser = database.Users.Where(c => c.UserName == currentUser).FirstOrDefault();
                if (qUser == null)
                    return null;
                if (string.IsNullOrEmpty(qUser.FirstName) || string.IsNullOrEmpty(qUser.LastName) || string.IsNullOrEmpty(qUser.Mobile))
                {
                    TempData["Style"] = "alert alert-warning text-center";
                    TempData["Msg"] = "جهت ادامه خرید شما باید اطلاعات کاربری خود را تکمیل نمایید";
                    return RedirectToAction(nameof(AccountController.Profile), "Account");
                }
                if (string.IsNullOrEmpty(qUser.PostalCode) || string.IsNullOrEmpty(qUser.City) || string.IsNullOrEmpty(qUser.Address))
                {
                    TempData["Style"] = "alert alert-warning text-center";
                    TempData["Msg"] = "جهت ادامه خرید شما باید اطلاعات محل سکونت خود را تکمیل نمایید";

                    return RedirectToAction(nameof(AccountController.PostInfo), "Account");
                }

                VmUser vm = new VmUser();
                vm.Address = qUser.Address;
                vm.City = qUser.City;

Eshop_AspCore/Views/Pay/CheckoutSendType.cshtml
@model VmUser
@{
    ViewData["Title"] = "CheckoutSendType";
    Layout = "~/Views/Shared/_Main_Layout.cshtml";
}

<style>

    .iranSansFont {
        font-family: 'IranSans';
    }
</style>
<div class="row">
    <div class="container">
        <br />
        <div class="panel panel-primary iranSansFont">
            <div class="panel-heading">
                <div class="panel-title text-center">تایید اطلاعات کاربری</div>
            </div>
            <div class="panel-body">
                <p>نام و نام خانوادگی : @(Model.FirstName + " " + Model.LastName)</p>
                <p>ایمیل : @Model.Email</p>
                <p>شماره موبایل : @Model.Mobile</p>
                <a asp-action="Profile" asp-controller="Account" class="btn btn-success">ویرایش اطلاعات کاربری</a>
                <hr />
                <p>استان : @Model.Province</p>
                <p>شهر : @Model.City</p>

                <p>ادرس محل سکونت : @(Model.Province + " - " + Model.City + " - " + Model.Address) &nbsp; کد پستی : @Model.PostalCode</p>

                <a asp-action="PostInfo" asp-controller="Account" class="btn btn-primary">ویرایش اطلاعات محل سکونت</a>
                <hr />
                <div>
                    @{
                        decimal finalPrice = ViewBag.FinalPrice;
                    }

                    <form method="get" asp-action="FinalCheckout" asp-controller="Pay">
                        <a asp-action="ShoppingCart" asp-controller="Pay" class="btn btn-warning ">مرحله قبل</a>
                        <input type="hidden" name="FinalPrice" value="@finalPrice" />
                        <input type="submit" name="NextLevel" value="مرحله بعد" class="btn btn-success pull-left " />
                        @*<a asp-action="ShoppingCart" asp-controller="Pay" class="btn btn-success pull-left ">مرحله بعد</a>*@
                    </form>

                </div>

            </div>

        </div>
    </div>
</div>

Eshop_AspCore/Views/Pay/FinalCheckout.cshtml
@{
    ViewData["Title"] = "FinalCheckout";
    Layout = "~/Views/Shared/_Main_Layout.cshtml";
}

<style>


    .iranSansFont {
        font-family: 'IranSans';
    }
</style>
<div class="row">
    <div class="container">
        <br />
        <div class="panel panel-primary iranSansFont">
            <div class="panel-heading">
                <div class="panel-title text-center">پرداخت هزینه</div>
            </div>
            <div class="panel-body">
                @if (@TempData["Message"] != null)
                {
                    <p class="@TempData["Style"]">@TempData["Message"]</p>
                }
                <p>مبلغ قابل پرداخت : @ViewBag.FinalPrice</p>

                @{ 
                    decimal finalPrice = ViewBag.FinalPrice;
                    string userId = ViewBag.UserID;
                    string transactionId = ViewBag.TransactionId;

                }
                <form asp-action="Payment" asp-controller="Pay">
                    <input type="hidden" name="FinalPrice" value="@finalPrice" />
                    <input type="hidden" name="UserID" value="@userId" />
                    <input type="hidden" name="TransactionId" value="@transactionId" />
                    <input type="submit" name="btnPay" value="پرداخت" class="btn btn-danger center-block" />

                </form>
            </div>
        </div>
    </div>
</div>

Eshop_AspCore/Views/Pay/PayResult.cshtml
@{
    ViewData["Title"] = "PayResult";
    Layout = "~/Views/Shared/_Main_Layout.cshtml";
}

@if (TempData["Message"] != null)
{
    <div class="alert alert-success">
        @TempData["Message"]
    </div>
}

Eshop_AspCore/Views/Pay/ShoppingCart.cshtml
@model IEnumerable<VmShoppingCart>
@{
    ViewData["Title"] = "ShoppingCart";
    Layout = "~/Views/Shared/_Main_Layout.cshtml";
    int RowCount = 1;
}


<style>
    .iranSansFont {
        font-family: iranSans;
    }
</style>

@if (Model.Count() > 0)
{
    <section id="cart_items">
        <div class="container">
            <div class="breadcrumbs">
                <ol class="breadcrumb">
                    <li><a href="/Home/Index">خانه</a></li>
                    <li class="active">سبد خرید</li>
                </ol>
            </div>

            <input type="submit" name="btnEmptyShopping" onclick="DeleteAllProduct()" value="خالی کردن سبد خرید" class="btn btn-danger center-block " />

            @*<form method="get" asp-action="RemoveShoppingCart" asp-controller="Pay" onsubmit=" return confirm('ایا میخواهید سبد خرید حذف شود؟')">
                    <input type="submit" name="btnEmptyShopping" value="خالی کردن سبد خرید" class="btn btn-danger center-block " />
                    <hr />
                </form>*@

            <div class="table-responsive cart_info">
                <table class="table table-condensed">
                    <thead>
                        <tr class="cart_menu">
                            <td>ردیف</td>
                            <td class="image">تصویر محصول</td>
                            <td class="description">نام محصول</td>
                            <td class="price">مبلغ</td>
                            <td class="quantity">تعداد</td>
                            <td class="total">جمع کل</td>
                            <td></td>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td style="font-family:iranSans;padding-top:50px">
                                    <label class="badge">
                                        @(RowCount++)
                                    </label>
                                </td>
                                <td class="cart_product">
                                    <a href=""><img src="@item.ProductImage" width="130" height="120" alt=""></a>
                                </td>
                                <td class="cart_description iranSansFont" style="padding-top:20px">
                                    <h4><a href="/Home/DetailsProduct?productId=@item.ProductId_FK">@item.ProductName</a></h4>
                                    <br />
                                    <p class="iranSansFont">کد محصول : @item.ProductId_FK </p>
                                </td>
                                <td class="cart_price" style="padding-top:30px">

                                    <p class="iranSansFont">@item.PriceWithOff تومان</p>
                                    <br />
                                    @if (item.OffProduct > 0)
                                    {
                                        <label class="badge alert-danger iranSansFont"> با @item.OffProduct % تخفیف</label>
                                    }
                                </td>
                                <td class="cart_quantity" style="padding-top:30px">

                                    <input class="cart_quantity_input iranSansFont" type="text" name="quantity" value="@item.ProductCount" autocomplete="off" size="2">

                                </td>
                                <td class="cart_total" style="padding-top:30px">
                                    <p class="cart_total_price iranSansFont">@(item.PriceWithOff * item.ProductCount) تومان</p>
                                </td>
                                <td class="cart_delete" style="padding-top:30px">

                                    <input type="button" name="btnDelete" onclick="DeleteSingleProduct(@item.ID)" value="حذف" class="btn btn-danger btn-xs" />
                                </td>
                            </tr>
                        }


                    </tbody>
                </table>
                @{

                    double maliat = ViewBag.Maliat;
                    double sumWeight = ViewBag.SumWeight;
                    decimal postagePrice = ViewBag.PostagePrice;
                    decimal SumPriceOff = ViewBag.SumPrice;
                    double tax = Convert.ToDouble(SumPriceOff) * maliat;
                    double maliatPriceOff = (tax + Convert.ToDouble(SumPriceOff));
                    decimal sump = Math.Ceiling(Convert.ToDecimal((maliatPriceOff / 100) * 100));
                    double priceWithTax = (maliat * 100);
                    decimal finalPrice = sump + postagePrice;
                }

                <form asp-action="CheckoutSendType" asp-controller="Pay" method="post">
                    <input type="hidden" name="FinalPrice" value="@finalPrice" />
                    <input type="submit" name="name" value="نهایی کردن سفارشات" class="btn btn-success" />
                    <input type="button" name="name" value="ادامه  خرید" class="btn btn-primary" />
                </form>
                @*@Html.ActionLink("نهایی کردن سفارشات", "CheckoutSendType", new { FinalPrice = finalPrice }, new { @class = "btn btn-success" });*@

            </div>

            <p class="alert alert-warning col-md-3 pull-right iranSansFont"> @priceWithTax % مالیات : @tax  تومان</p>
            <p class="alert alert-info text-left pull-left container iranSansFont">
                جمع کل سبد خرید : @SumPriceOff  تومان
            </p>

            <p class="alert alert-danger text-left pull-left  container iranSansFont">
                <span class="text-right pull-right badge" style="font-size:medium"> وزن کالا :  @sumWeight گرم</span>&nbsp; &nbsp;  هزینه ارسال با احتساب وزن کالا : @postagePrice  تومان
            </p>
            <p class="alert alert-success text-left pull-left container iranSansFont">
                مبلغ قابل پرداخت : @finalPrice  تومان
            </p>

        </div>
    </section>
}
else
{
    <br />
    <div class="alert alert-danger center-block text-center iranSansFont">
        سبد خرید شما خالی می باشد
    </div>

}

<script>
    function DeleteSingleProduct(id) {
        if (confirm('آیا میخواهید این محصول از سبد خرید حذف شود') == true) {
            $.ajax(
                {
                url: "/Pay/RemoveProductOfShoppingCart/" + id,
                type: "Post",
                data: { shoppingId: id },
                complete: function () {

                    location.reload();
                    @*$('#cart_items').load('@(Url.Action("ShoppingCart","Pay",null))');*@
                }
            })
        }
    }
    function DeleteAllProduct() {
        if (confirm('آیا میخواهید تمامی محصولات از سبد خرید حذف شوند') == true) {
            $.ajax({
                url: "/Pay/RemoveAllProductOfShoppingCart/",
                type: "Get",
                data:"",
                complete: function () {
                    location.reload();
                }
            })
        }
    }
</script>